### ISSUE TITLE
Issues on Create-a-complete-website-with-navigation-branch

### ISSUE THREAD

**Issue by OLIPLICHE** [Rustamxon7/Awesome-books#5]
**Issues**

- You did a marvelous job, I like it ⭐⭐⭐⭐ 
- Your codes are clean
- There is one blanc line at the bottom of your HTML code. I suggest that you should avoid blanc or empty lines if there is not any comment to make.  
- Congratulations 🥇🥇🥇

**Comment by Busiwa24** [comment]
Awesome job
-Very elaborate and well-written code
